/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.14.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as auth_credentials_login from "../auth/credentials_login.js";
import type * as auth_reset_password from "../auth/reset_password.js";
import type * as auth_verify_email from "../auth/verify_email.js";
import type * as auth from "../auth.js";
import type * as documents_mutation from "../documents/mutation.js";
import type * as documents_query from "../documents/query.js";
import type * as http from "../http.js";
import type * as user from "../user.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "auth/credentials_login": typeof auth_credentials_login;
  "auth/reset_password": typeof auth_reset_password;
  "auth/verify_email": typeof auth_verify_email;
  auth: typeof auth;
  "documents/mutation": typeof documents_mutation;
  "documents/query": typeof documents_query;
  http: typeof http;
  user: typeof user;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
